INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'ANTIOQUIA', '5', '05');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'ATLANTICO', '8', '08');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'BOGOTA', '11', '11');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'BOLIVAR', '13', '13');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'BOYACA', '15', '15');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CALDAS', '17', '17');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CAQUETA', '18', '18');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CAUCA', '19', '19');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CESAR', '20', '20');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CORDOBA', '23', '23');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CUNDINAMARCA', '25', '25');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CHOCO', '27', '27');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'HUILA', '41', '41');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'LA GUAJIRA', '44', '44');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'MAGDALENA', '47', '47');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'META', '50', '50');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'NARIÑO', '52', '52');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'N. DE SANTANDER', '54', '54');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'QUINDIO', '63', '63');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'RISARALDA', '66', '66');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'SANTANDER', '68', '68');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'SUCRE', '70', '70');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'TOLIMA', '73', '73');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'VALLE DEL CAUCA', '76', '76');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'ARAUCA', '81', '81');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'CASANARE', '85', '85');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'PUTUMAYO', '86', '86');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'SAN ANDRES', '88', '88');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'AMAZONAS', '91', '91');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'GUAINIA', '94', '94');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'GUAVIARE', '95', '95');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'VAUPES', '97', '97');
INSERT INTO `gen_departamento` (`codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 'VICHADA', '99', '99');