INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8000000921','','SEGUROS BETA S.A. CORREDORES DE SEGUROS');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'9008149161','','BERKLEY INTERNATIONAL SEGUROS COLOMBIA S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'860026182','','ALLIANZ S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600377079','','CHARTIS SEGUROS COLOMBIA S.A');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600274041','','COMPAÑIA CENTRAL DE SEGUROS');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'9002004353','','CARDIF COLOMBIA SEGUROS GENERALES S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'9002004353','','CARDIF COLOMBIA SEGUROS GENERALES');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8917000379','','MAPFRE SEGUROS GENERALES DE COLOMBIA S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8909034079','','COMPAÑÍA SURAMERICANA DE SEGUROS S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8903004658','','CONDOR S. A. COMPAÑÍA DE SEGUROS GENERALES');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8903003832','','GRUPO COLMENA CAPITALIZADORA COLMENA S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8605246546','','ASEGURADORA SOLIDARIA DE COLOMBIA');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600703349','','COMPAÑÍA ASEGURADORA DE FIANZAS S. A. CONFIANZA');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600399880','','LIBERTY SEGUROS S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600382991','','PAN AMERICAN DE COLOMBIA COMPAÑÍA DE SEGUROS DE VIDA');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600377079','','AIG SEGUROS GENERALES S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600370136','','COMPAÑÍA MUNDIAL DE SEGUROS');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600345205','','CHUBB DE COLOMBIA COMPAÑIA DE SEGUROS S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600319798','','SEGUROS DE VIDA ALFA S. A. SEGUROS GENERALES');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600284155','','LA EQUIDAD SEGUROS GENERALES ORGANISMO COOPERATIVO');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600265186','','ACE SEGUROS S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600261825','','ALLIANZ SEGUROS S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600221375','','COMPAÑÍA DE SEGUROS DE VIDA AURORA S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600111536','','POSITIVA COMPAÑÍA DE SEGUROS (ANTIGUA PREVISORA)');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600095786','','SEGUROS DEL ESTADO S.A. SEGUROS GENERALES');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600091959','','SEGUREXPO DE COLOMBIA S. A. ASEGURADORA DE CREDITO');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600048756','','GENERALI COLOMBIA SEGUROS GENERALES S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600025340','','QBE SEGUROS S.A');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600025279','','AGRICOLA DE SEGUROS S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600025057','','ROYAL Y SUN ALLIANCE SEGUROS (COLOMBIA) S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600024002','','LA PREVISORA S. A. COMPAÑÍA DE SEGUROS');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600023985','','AIG COLOMBIA SEGUROS DE VIDA S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600021846','','SEGUROS COLPATRIA S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8600021807','','SEGUROS COMERCIALES BOLÍVAR S.A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8110191907','','MAPFRE CREDISEGURO S. A.');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8002261753','','COLMENA RIESGOS PROFESIONALES COLMENA');
INSERT INTO tte_aseguradora (codigo_aseguradora_pk, numero_identificacion, digito_verificacion, nombre) VALUES (0,'8002260984','','BBVA SEGUROS COLOMBIA S. A. S');