INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1212','DONG-A');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1100','CNJ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('2337','BAIC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1134','DFAC DONG FENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1078','T-KING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1076','GVMCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1075','GBMCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1074','INDUSTRY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1073','FENIX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1072','GAME');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1071','SANYOU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1070','MIKILON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1069','FASTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1068','MOFFETT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1067','SELVAXTREMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1066','JUNCHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1065','UD TRUCKS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1064','POLARSUN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1063','SINOTRUK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1062','ASIA HERO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1061','ALFA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1060','ZILI MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1059','JAUNCE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1058','HONOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1057','AWS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1056','LANGQING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1055','SENKE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1054','XGJAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1053','BERA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1052','GSMOON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1051','OLIYA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1050','DFSK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1049','ESCORPIO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1048','KING LONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1047','DADI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1046','HUANGHAI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1045','ZNA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1044','HANLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1043','YAXING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1042','OULING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1041','BENLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1040','MAHINDRA DURO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1039','CLC MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1038','LUCKY LION');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1037','CARPATI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1036','VMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1035','SHELBY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1034','HAORI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1033','TAYLOR DUNN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1032','D LONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1031','LOVOL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1030','THOMAS BUILT BUSES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1029','HUNTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1028','KMO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1027','DETROIT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1026','E-ONE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1025','DFA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1024','JBC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1023','ETX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1022','JIAJUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1021','ADVANCE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1020','JLC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1019','YADEA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1018','HPOWER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1017','ENERGY MOTION');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1016','JIASHITE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1015','BYVIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1014','PACIFIC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1013','GALAXI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1012','TAO TAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1011','WANCH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1010','YGM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1009','LINGKEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1008','JIANGSU SINSKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1007','AWS - ALIEN WORK SHOP');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1006','TRACTOCASA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1004','HISUN TIGER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1003','VOLDA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1002','SMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1001','HAIMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1000','TORNADO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('999','GREENWHEEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('998','YAKEY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('997','KHOOBRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('996','ESSEX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('995','ASA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('994','ISHIMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('993','MITSUBISHI FUSO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('992','YONGKANG EASY VEHICLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('991','MANZINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('990','MOTOKART');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('989','BARHOG/DADYW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('988','SM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('987','SUMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('986','AVA MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('985','BOUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('984','SHACMAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('983','HUALIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('982','TEAM RYDER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('981','AUTECO VICTORY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('980','SANLEE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('979','HENSIM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('978','XRP SAIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('977','FUXIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('976','TEMPEST');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('975','CFMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('973','HIGER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('972','TOURING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('971','DCEC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('970','ARCTIC CAT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('969','MALAGUTI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('968','WANHU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('967','YUTONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('966','FIVER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('965','LIEBHERR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('964','HOREX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('963','PERLINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('962','MOXI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('961','MAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('960','DRESSER HAULPAK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('959','AUTECO KYMCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('958','AUTECO BAJAJ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('957','SANY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('956','BOMAG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('955','THOMAS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('954','STERLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('953','ZHONGHUA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('952','YITAKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('951','VOSHUD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('950','VEDETTE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('949','UNDERBONE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('948','TRADER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('947','TONGBAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('946','TANDEM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('945','T.J.C.');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('944','STUTZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('943','STAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('942','SSANGYANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('941','SKANIA VABIF');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('940','SCOUTY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('939','ROMAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('938','ROCAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('937','PAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('936','PANDA CHUNZOHN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('935','LUAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('934','LLOYD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('933','JINLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('932','IFG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('931','FODEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('930','BAW ZHAN QI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('929','AUTO BIANCHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('928','AEOLUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('927','WEST WARRIOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('926','REGAL RAPTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('925','PRATOO Y FORNE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('924','HAOJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('923','CIXI KONCEO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('922','HONGXING NOBLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('921','ALLARD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('920','ALL STATE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('919','ZUK NYSA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('918','ZUK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('917','ZQ MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('916','ZIU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('915','ZHONGYU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('914','ZHONGNENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('913','ZHAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('912','ZENA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('911','YLM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('910','XSG ING QIJITUA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('909','XINTIAN KINROAD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('908','XINLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('907','XINGLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('906','WSK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('905','WORLDSTAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('904','WORD LA FRANCE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('903','WLLHELMSHAVEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('902','WINCHEMG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('901','WAJAX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('900','WAGONNER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('899','VONROAD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('898','VOGUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('897','VANGUARD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('896','VALKYRIE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('895','VALIANT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('894','UFO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('893','TULA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('892','TOYOPET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('891','TONGYU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('890','TMD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('889','TGA-200-G');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('888','TEMPO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('887','TATRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('886','TANTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('885','TALBOT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('884','SUPERMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('883','SUNASA QINGQI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('882','SUMO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('881','STIRES VM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('880','STEINBOCK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('879','SST');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('878','SRFHUAIGE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('877','SP@ZZIO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('876','SOYAT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('875','SONZINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('874','SONIKA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('873','SOLARI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('872','SKYTEAM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('871','SHUANGSHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('870','SHUANGHUAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('869','SHERPA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('868','SHANYANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('867','SHANGLI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('866','SERVAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('865','SEAGRAVE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('864','SCAMMELL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('863','SAURER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('862','SANGLIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('861','SANDI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('860','SAAB');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('859','ROSENBAUER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('858','REVA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('857','RABBIT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('856','PREFECT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('855','POWER WAGON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('854','PLANETA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('853','PEXMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('852','PASSO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('851','ORION');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('850','ORANGE COUNTY CHOPPERS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('849','NYK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('848','NEW HYSTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('847','NEUTRAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('846','N.S.U');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('845','MUHCK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('844','MUDAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('843','MOTOCARRIER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('842','MONIKA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('841','MOBYLESTTE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('840','MNHCK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('839','MG MIDGET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('838','MAZAKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('837','MAYFLOWER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('836','MAXWELL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('835','MASTER CRAFT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('834','MARQUASS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('833','MARCHETTI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('832','M.G.U');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('831','LINGBEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('830','LINDE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('829','LIBA MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('828','LIANMEI MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('827','LEY LAND');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('826','LEE SCUSTÓN COACHES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('825','L.A.I');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('824','KROSON SOPORTES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('823','KONTIO SISO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('822','KOMAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('821','KARPETAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('820','KANABIS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('819','JUNGHEINRICH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('818','JUMBO DE LLANTAS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('817','JIN JIAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('816','ISLO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('815','IKARUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('814','I.M.V');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('813','HUSABERG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('812','HUPMOBILE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('811','HUAWIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('810','HOSIN SOPORTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('809','HESTIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('808','HAOJUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('807','HALLA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('806','GRUBER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('805','GREMLIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('804','GRANE CARRIER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('803','GRAHAN PAUGE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('802','GOGOMOVIL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('801','GERLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('800','FULDAMOBIL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('799','FRAZER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('798','FLEXIBLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('797','FIBRAVAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('796','FARSPEED');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('795','FANTIC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('794','F.N');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('793','EZGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('792','E-TON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('791','EP');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('790','EM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('789','ELEPHANT POWER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('788','EL SOL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('787','ECO CITI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('786','DTV');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('785','DIVICO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('784','DEMAG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('783','DE LA HAYE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('782','DASHA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('781','DAIMLER BENZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('780','DAF');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('779','DACC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('778','CRUISERN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('777','CROSLEY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('776','CONSUL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('775','COLT LANCER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('774','CLAUSSON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('773','CHITUMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('772','CHINA MOTORCYCLES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('771','CENTAURS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('770','CAMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('769','C.C.C.');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('768','BRISA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('767','BRAND');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('766','BOSA BOSHIE NIKE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('765','BENELLI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('764','BANTAM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('763','BAKER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('762','BAIKANCAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('761','AYCO ZONGSHEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('760','AUTOKRAFT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('759','ASPT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('758','ARABELLA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('757','APOLLO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('756','AMPLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('755','AMPHICAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('754','ALVIS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('753','ALFARO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('752','AG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('751','AC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('750','MASERATI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('749','GO KART');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('748','CEZET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('747','DANUVIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('746','CZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('745','ZUNDAPP');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('744','HORNET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('743','VOSJOB');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('742','VERKHOVINA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('741','TOWMOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('740','TENNAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('739','TCUMSON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('738','STAVOSTROJ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('737','PHW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('736','OSSA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('735','MOBILIFT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('734','LIMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('733','L.R.');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('732','KAELBLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('731','JINGPIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('730','JINBEI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('729','DESTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('728','DELKRON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('727','CCITTA REBEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('726','TADANO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('725','PIQUERSA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('724','PINZ GAUER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('722','PANZER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('720','MATBRO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('719','MARINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('718','LINK BELT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('717','LEE BOY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('716','KOBELCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('715','KATO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('714','ISEKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('713','FURUKAWA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('712','BELL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('711','RHINO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('709','BUGGY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('708','CARBONER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('705','ZUNK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('704','ZODIAC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('703','ZIP STAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('702','ZIGMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('701','ZID');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('700','ZHENG LI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('699','ZHEJIANG HANGCHA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('698','ZETOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('697','ZEPHYR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('696','YUMBO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('695','YUEJIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('694','YUANDA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('693','YONKANG XINGYUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('692','YIBEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('691','YAMASAKY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('690','YALE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('689','XCMG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('688','WKT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('687','WESTERN STAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('686','WARZAWA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('685','VOGELE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('684','VISAIL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('683','VALTRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('682','VALMET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('681','USA MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('680','UNIVERSAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('679','UNIMOG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('678','TRIWIL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('677','TONARO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('676','THUNDER CYCLE DESIGN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('675','TEREX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('674','TCM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('673','SUNDIRO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('672','SUM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('671','SUKIDA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('670','STEYR DAIMLER PUCH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('669','SMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('668','SKYMAX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('667','SKINGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('666','SINOTRUK HOWO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('665','SHINERAY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('664','SHANGHAI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('663','SAURON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('661','SANFENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('660','SAME');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('659','ROSCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('658','ROBUR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('657','RLX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('656','REVTECH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('655','RANGE ROVER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('654','RAMIREZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('653','QIANJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('652','POWERMAX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('651','POCLAIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('650','PIAGGIO ZONGSHEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('649','PETTIBONE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('648','PARCE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('647','P Y H');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('646','OSHKOSH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('645','OAKLAND');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('644','NUFFIELD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('643','NON PLUS ULTRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('642','NIMBUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('641','NEW KING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('640','NEW HOLLAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('639','MV AGUSTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('638','MOTOBECAME');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('637','MINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('636','MGB');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('635','META');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('634','MERLO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('633','MC CORMICK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('631','MATCHELSS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('630','MASEY FERGUSON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('629','MARUTI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('628','MARMON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('627','MANCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('626','MADVAC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('625','LORAIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('624','LMX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('623','LIUGONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('622','LITTLE GIANT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('621','LINCOLN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('620','KRUPP');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('619','KRAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('618','KONCEO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('617','KOMATSU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('616','KITOMI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('614','KING LINFT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('613','KAZUMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('612','KALMAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('611','KAISER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('609','JIRY SISU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('608','JINGLONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('607','JIANGXI CAMPELL CO.');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('606','JIANGSU KINROAD XINTIAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('605','JIANGNAN GLOW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('604','JIANGLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('603','JIANG CHANGHE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('602','JHONSTON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('601','JHON DEERE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('600','JCB');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('599','JAVELINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('598','JAINSHE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('597','JACKEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('596','INVICTUS MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('595','INGERSOLL RAND');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('594','INDIAN CHIEF');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('593','INCALCU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('592','HYSTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('591','HUMMER ZONGSHEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('590','HUBER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('589','HITACHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('588','HISTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('587','HILIGHT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('586','HERRAGRO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('585','HELI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('584','HARMON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('583','HARDLAND');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('581','GROVE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('580','GRAM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('578','GOLDEN DRAGON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('577','GHA-2');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('576','GENERAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('575','GAZELLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('574','GALION');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('573','FYM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('572','FWD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('571','FUTURE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('570','FORMULA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('569','FONA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('568','FIORI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('567','FIAT ALLIS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('566','FENCHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('564','FEDERAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('563','FAMY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('562','FAILING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('561','EZLIFE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('560','EXPRESS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('559','EXCELSIOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('558','EVO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('557','EUCLID');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('556','ERNEST GRUBER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('555','ENERGY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('554','ENCAVA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('553','ELGIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('552','ELECTRIC STAR ATV ENERGY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('551','EBTELECTRIC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('550','EASTMAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('549','EAGLE AMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('548','EAGLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('547','E.D. ETNYRE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('546','DYNACOLT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('545','DUST');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('544','DRESSER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('543','DOMINGUEZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('542','DINAPAC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('541','DIECI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('540','DIAMOND');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('539','DAYUN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('538','DAVID BROWN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('537','CUSTOM CHROME');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('536','CSEPEL-CUMMINS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('535','CROWN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('534','CONCORD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('533','COMET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('532','COMANDO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('531','COLOMBIANA DE CHASISES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('530','CLUB CAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('529','CLARCK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('528','CICLONE USA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('527','CHONGQUING YUAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('526','CHONGQING ZONGSHEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('525','CHINSU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('524','CHARMING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('523','CHARLY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('522','CHANGLIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('521','CHAMPION');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('520','CATFLYER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('519','CATERPILLAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('518','CASE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('517','CARTER BROTHERS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('516','CARIBE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('515','CAPACITY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('513','CAMECO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('512','BUGENI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('511','BUCYRUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('510','BRONTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('509','BRIDGE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('508','BOUSER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('507','BONSER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('506','BODYWORK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('505','BOBCAT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('504','BLUE STONE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('503','BLAW KNOX');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('502','BIMOTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('501','BIANCHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('500','BETTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('499','BETA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('498','BAW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('497','BAUKEMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('496','BASHAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('495','BARBER GREENE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('494','BAODIAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('493','BACCIO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('492','ASTRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('491','APELCO GEN-MTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('490','AP PIAGGIO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('489','AMW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('488','AMM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('487','ALPS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('486','ALLIS CHALMERS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('485','ALLAD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('484','ADDO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('483','ACM-ZHONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('482','ACE MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('481','ACE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('480','ACCESS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('479','A.J.S');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('478','XINKAI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('477','WUZHENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('476','WORKMAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('475','TX MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('474','TELCOLINE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('473','TALON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('472','SHIJIAZHUANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('471','REBELLIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('470','NIKITA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('469','MOTO MORINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('468','KYNLON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('467','JIN JIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('466','JIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('465','IOTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('464','GUZZI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('463','GONOW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('462','FUDEPAI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('461','EAGLE CARGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('460','DAIFO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('459','BIG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('458','AKITA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('457','ITALIKA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('456','YIBEN-YBFALCON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('455','ZAHAV');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('454','SQ RACING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('453','FAW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('452','OROMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('451','EKA MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('450','ZNEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('449','TIXXON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('448','DONG FENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('447','ROSSETTI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('446','RIDER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('445','GWM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('444','FUXIANDA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('443','KANCHAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('442','WCR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('441','TERRA JET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('440','PANTERA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('439','JINFENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('438','WUYANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('437','MD BIKES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('436','ATM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('435','BMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('434','KANDI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('433','KINGLONG HIGER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('432','XINGUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('431','CHANGFENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('430','SUKYAMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('429','ZOTYE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('428','ZHEJIANG LINGTIAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('427','HAOMEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('426','TVS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('425','HY MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('424','REX MOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('423','BOURGET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('422','FASTER 301 CHOIPERS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('421','MTK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('420','YAKIMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('419','DFM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('418','SCOOTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('417','POLARIS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('416','ZHUJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('415','ZHEJIANG QIANJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('414','HAMMER HEAD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('413','ACB');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('412','YUAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('411','XL XINLING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('410','VENTIE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('409','XINGYUE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('408','WEST');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('407','BRP/CAN AM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('406','NEW ERA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('405','FRIBEST');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('404','TONGKO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('403','SAEHAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('402','HAILI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('401','NITRO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('400','WULING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('399','SATURN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('398','PUMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('397','PIERCE ARROW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('396','LA SALLE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('395','HUMBERT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('394','GURGEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('393','BUYANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('392','CUSHMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('391','COBRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('390','BRITISH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('389','VERUCCI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('388','JMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('387','SONGSHENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('386','JBWCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('385','HAOJIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('384','QJ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('383','TMEC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('382','VENOM MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('381','UNITED MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('380','SHINERAY MOTOS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('379','ACCURO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('378','ROKETA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('377','YAMATI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('376','CNENLON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('375','FOTON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('374','SANYA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('373','AVANTI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('372','JOYNER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('371','ROYAL ENFIELD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('370','SYM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('369','U.S.W.MOTORS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('368','ZHONGXING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('367','BORGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('366','JAC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('365','JONWAY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('364','BUELL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('363','TYCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('362','GALARDI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('361','RENNO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('360','APRILIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('359','USW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('358','MOTOR UNO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('357','KINROAD XINTIAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('356','AUTOCAR WHITE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('355','SUMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('354','ZHEJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('353','KEEWAY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('352','XISPA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('351','POLARIS ATV');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('350','GENESIS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('349','GREAT WALL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('348','FIRENZE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('347','URAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('346','CMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('345','KYOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('344','HUONNIAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('343','ARGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('342','CHONGQING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('341','SKOOT MOTORCYCLES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('340','UNISON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('339','YINGANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('338','FUTONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('337','BEST');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('336','ZONGSHEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('335','JMSTAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('334','WANXIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('333','WONJAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('332','ATV');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('331','ARIEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('330','UKM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('329','HALLEY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('328','MORGAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('327','KINROAD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('326','WALTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('325','REAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('324','JUNESUN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('323','MZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('322','KYMCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('321','SACHS BIKES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('320','JIANGSU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('319','MC MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('318','AUPACO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('317','KAYAK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('316','PASAGGIO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('315','SKYGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('314','DUKAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('313','BYD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('312','CPI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('311','HONLEI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('310','ACCURA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('309','JINAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('308','TITANIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('307','XIALI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('306','GOMOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('305','VENTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('304','KAZUKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('303','LONCIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('302','CHANGHE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('301','VICTORY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('300','MINI POCKET BIKE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('299','SIGMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('298','AMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('297','JET UKM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('296','CHANGJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('295','KINLON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('294','SAIC WULING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('293','PIONEER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('292','AYCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('291','JEZHANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('290','SHENGQIBAO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('289','CHERY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('288','CHANA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('287','GEELY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('286','QINGQI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('285','MAX MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('284','LINHAI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('283','HAFEI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('282','OKLAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('281','CHANGAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('280','GAS GAS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('279','DINLI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('278','SAIC CHERY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('277','AKT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('276','KOREMOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('275','LIFAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('274','VARZI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('273','SMART');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('272','TATA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('271','LML');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('270','WHITE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('269','VOSJOD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('268','THAMES');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('267','TRABANT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('266','SAVA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('265','SINGER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('264','SUMBEAM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('263','SANGLAS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('262','SAMSUNG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('261','RONART');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('260','PANHARD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('259','PANNONIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('258','PACER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('257','MOTOGUZZI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('256','CARABELLA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('255','BOCXOD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('254','BULTACO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('253','BABETA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('252','MAHINDRA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('251','GILERA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('250','INDIAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('249','VOSKHOD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('248','ITALJET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('247','NORTON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('246','B.S.A');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('245','VESPA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('244','VAUSHALL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('243','ZUMY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('242','DAYANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('241','INFINITI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('240','BOMBARDIER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('239','KINETIC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('238','PRINCE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('237','SPARTAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('236','RAF');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('235','MG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('234','DUCATI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('233','PETERBILT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('232','AGRALE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('231','XINGFU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('230','BEISUTE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('229','POLONEZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('228','BAJAJ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('227','KTM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('226','HUMMER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('225','YUGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('224','JIANSHE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('223','DAELIM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('222','COLMOVE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('221','PIAGGIO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('220','WARZAMA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('219','TRIUMPH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('218','STUDEBAKER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('217','SSANGYONG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('216','SCANIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('215','REO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('214','PORSCHE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('213','PEGASSO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('212','MINICORD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('210','LEXUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('209','JAWA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('208','HYUNDAI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('207','HENRY J');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('206','DERBY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('205','BEIJING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('204','ROA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('202','AMERICAN MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('201','ALEKO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('200','F.S.O.');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('198','PACKARD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('196','NECKAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('195','MURAVEY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('192','MOSKOVICH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('191','MAGIRUS DEUTZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('190','MAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('188','LOTUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('185','LAMBORGHINI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('184','KIAMASTER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('181','ISO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('179','IFA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('178','HUDSON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('176','HILLMAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('175','HOHOLDEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('171','FAUN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('169','FREIGHTLINER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('167','FORDSON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('165','EDSEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('163','DKW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('158','COMMER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('156','BARREIROS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('154','BERLIET');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('153','BEDFORD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('151','BUSSING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('150','BENTLEY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('149','BORG WARD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('148','BROCK WAY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('146','CHECKER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('144','AVIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('143','AUTO UNION');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('142','ASTON MARTIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('139','AUDI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('138','ABARTH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('136','SEAT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('135','SISU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('130','QJIANG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('129','WILLCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('128','RAMBLER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('127','MORRIS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('126','WARTBURG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('125','NASH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('123','JINCHENG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('121','EBRO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('120','PUCH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('119','KAMAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('118','CORCEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('115','ROVER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('114','FARGO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('113','MONTESA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('112','HUALI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('110','ZASTAVA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('108','JIALING');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('104','BELARUS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('101','TAM');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('97','KUBOTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('95','VIASA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('91','GMC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('89','HUSQVARNA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('86','HYOSUNG');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('85','DELTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('84','GEO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('83','DINA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('76','HINO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('75','DESOTO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('74','AUTOCAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('73','AUSTIN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('72','HERO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('71','MINSK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('69','LAMBRETA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('68','IVECO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('67','KENWORTH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('66','WILLYS');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('65','CAGIVA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('64','MACK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('63','ASIA MOTOR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('62','INTERNATIONAL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('61','AUTECO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('60','HARLEY DAVIDSON');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('57','KAWASAKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('56','YAMAHA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('54','FORD');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('53','CHRYSLER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('52','SUZUKI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('51','LAND ROVER');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('50','JEEP');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('49','ISUZU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('48','OPEL');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('47','MERCURY');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('46','ARO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('45','UAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('44','GAZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('42','DAIHATSU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('41','CITROEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('40','SKODA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('39','VOLGA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('37','TAVRIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('36','OLTCIT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('35','LADA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('34','DACIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('33','JAGUAR');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('32','ROLLS ROYCE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('30','MERCEDES BENZ');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('29','FERRARI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('28','BMW');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('27','ALFA ROMEO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('26','VOLVO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('25','TOYOTA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('24','PONTIAC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('23','MITSUBISHI');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('22','BRONCO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('21','HONDA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('20','CADILLAC');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('19','BUICK');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('18','DATSUN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('17','SUBARU');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('16','PEUGEOT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('15','NISSAN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('14','LANCIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('13','OLDSMOBILE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('12','PLYMOUTH');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('11','SIMCA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('10','DODGE');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('9','VOLKSWAGEN');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('8','RENAULT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('6','MAZDA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('5','KIA');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('3','FIAT');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('2','DAEWOO');
INSERT INTO tte_marca (codigo_marca_pk,nombre) VALUES ('1','CHEVROLET');