INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (1, 1, 'ANTIOQUIA', '5', '05');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (2, 1, 'ATLANTICO', '8', '08');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (3, 1, 'BOGOTA', '11', '11');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (4, 1, 'BOLIVAR', '13', '13');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (5, 1, 'BOYACA', '15', '15');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (6, 1, 'CALDAS', '17', '17');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (7, 1, 'CAQUETA', '18', '18');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (8, 1, 'CAUCA', '19', '19');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (9, 1, 'CESAR', '20', '20');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (10, 1, 'CORDOBA', '23', '23');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (11, 1, 'CUNDINAMARCA', '25', '25');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (12, 1, 'CHOCO', '27', '27');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (13, 1, 'HUILA', '41', '41');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (14, 1, 'LA GUAJIRA', '44', '44');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (15, 1, 'MAGDALENA', '47', '47');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (16, 1, 'META', '50', '50');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (17, 1, 'NARIÑO', '52', '52');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (18, 1, 'N. DE SANTANDER', '54', '54');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (19, 1, 'QUINDIO', '63', '63');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (20, 1, 'RISARALDA', '66', '66');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (21, 1, 'SANTANDER', '68', '68');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (22, 1, 'SUCRE', '70', '70');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (23, 1, 'TOLIMA', '73', '73');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (24, 1, 'VALLE DEL CAUCA', '76', '76');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (25, 1, 'ARAUCA', '81', '81');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (26, 1, 'CASANARE', '85', '85');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (27, 1, 'PUTUMAYO', '86', '86');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (28, 1, 'SAN ANDRES', '88', '88');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (29, 1, 'AMAZONAS', '91', '91');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (30, 1, 'GUAINIA', '94', '94');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (31, 1, 'GUAVIARE', '95', '95');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (32, 1, 'VAUPES', '97', '97');
INSERT INTO `gen_departamento` (`codigo_departamento_pk`, `codigo_pais_fk`, `nombre`, `codigo_dane`, `codigo_dane_mascara`) VALUES (33, 1, 'VICHADA', '99', '99');