INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EAS016','','890904996-1','Empresas Públicas de Medellín Departamento Médico','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EAS027','','800112806-2','Fondo de Pasivo Social de Ferrocarriles','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS001','','830113831-0','Aliansalud EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS002','','800130907-4','Salud Total S.A.','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS003','','800140949-6','Cafesalud EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS005','','800251440-6','E.P.S Sanitas','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS008','','860066942-7','Compensar Entidad Promotora de Salud','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS010','','800088702-2','EPS Sura','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS012','','890303093-5','Comfenalco Valle EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS016','','805000427-1','Coomeva EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS017','','830003564-7','Famisanar','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS018','','805001157-2','Servicio Occidental de Salud S.O.S. S.A.','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS023','','830009783-0','Cruz Blanca S.A','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS033','','830074184-5','Saludvida S.A EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS037','','900156264-2','Nueva EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'MIN001','','900462447-5','Fondo de Solidaridad y Garantía Fosyga','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'MIN002','','900462447-5','Fondo de Solidaridad y Garantía Fosyga','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'MIN003','','900462447-5','Fondo de Solidaridad y Garantía Fosyga','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES005','','890102257-3','Universidad del Atlántico','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES006','','890203183-0','Universidad Industrial de Santander','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES007','','890399010-6','Universidad del Valle','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES008','','899999063-3','Universidad Nacional de Colombia','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES009','','891500319-2','Universidad del Cauca','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES011','','890980040-8','Universidad de Antioquia','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES012','','891080031-3','Universidad de Córdoba','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'RES014','','891800330-1','Universidad Pedagógica y Tecnológica de Colombia - UPTC','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSC03','','8001409496','Cafesalud Entidad  Promotora de Salud S.A','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSC22','','899999107','Entidad Administradora de Régimen Subsidiado Convida','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSC25','','891856000','Capresoca EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSC34','','900298372','Capital Salud EPSS S.A.S.','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSIC1','','824001398','Asociación de Cabildos Indígenas del Cesar “Dusakawi”','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSIC2','','812002376','Asociación de Cabildos Indígenas del Resguardo Indígena Zenú de San Andrés de Sotavento Córdoba - Sucre "Manexka"','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSIC3','','817001773','Asociación Indígena del Cauca - A.I.C.','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSIC4','','839000495','Entidad Promotora de Salud Anas Wayuu EPSI','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSIC5','','837000084','Entidad Promotora de Salud Mallamas EPSI','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPSIC6','','809008362','Entidad Promotora de Salud Pijaosalud EPSI','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC02','','811004055','Empresa Mutual para el desarrollo integral de la salud E.S.S. Emdisalud ESS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC07','','806008394','Asociación Mutual Ser Empresa Solidaría de Salud ESS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC18','','814000337','Asociación Mutual Empresa Solidaria de Salud de Nariño E.S.S. Emssanar E.S.S.','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC24','','800249241','Cooperativa de Salud y Desarrollo Integral de la Zona Sur Oriental de Cartagena  b aLtda.  Coosalud E.S.S.','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC33','','804002105','Cooperativa de Salud Comunitaria "Comparta"','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC62','','817000248','Asociación Mutual La Esperanza Asmet Salud','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC76','','818000140','Asociación Mutual Barrios Unidos de Quibdó E.S.S. AMBUQ','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'ESSC91','','832000760','Entidad Cooperativa Solidaria de Salud Ecoopsos','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'EPS 040','','900604350','Caja de Compensación Familiar de Antioquía - Comfama - Hoy Savia Salud EPS','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC09','','891800213','Comfaboy EPS-CCF de Boyacá','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC15','','891080005','Comfacor EPS – CCF de Córdoba','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC20','','891600091','Comfachoco – CCF del Chocó','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC23','','892115006','Caja de Compensación Familiar de La Guajira','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC24','','891180008','Comfamiliar Huila EPS – CCF','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC27','','891280008','Comfamiliar de Nariño EPS – CCF','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC33','','892200015','Comfasucre EPS-CCF de Sucre','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC53','','860045904','Comfacundi - CCF de Cundinamarca','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCFC55','','890102044','Cajacopi Atlántico  - CCF','',0,0,1,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'230201','','800229739-0','Protección','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'230301','','800224808-8','Porvenir','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'230901','','800253055-2','Old Mutual Fondo de Pensiones Obligatorias','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'230904','','830125132-2','Old Mutual Fondo Alternativo de Pensiones','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'231001','','800227940-6','Colfondos','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'25-2','','860007379-8','Caja de Auxilios y de Prestaciones de ACDAC','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'25-3','','899999734-7','Fondo de Previsión Social del Congreso','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'25-7','','800216278-0','Pensiones de Antioquia','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'25-14','','900336004-7','Administradora Colombiana de Pensiones Colpensiones','',0,0,0,1,1);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-4','','860002183-9','A.R.L. Seguros de Vida Colpatria S.A.','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-7','','860002503-2','Compañía de Seguros Bolívar S.A.','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-8','','860022137-5','Seguros de Vida Aurora','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-17','','860503617-3','ARP Alfa','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-18','','860008645-7','Liberty Seguros de Vida S.A.','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-23','','860011153-6','Positiva Compañía de Seguros','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-25','','800226175-3','Colmena Riesgos Profesionales','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-28','','800256161-9','ARL Sura','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-29','','830008686-1','La Equidad Seguros de Vida','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'14-30','','830054904-6','Mapfre Colombia Vida Seguros S.A','',1,0,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF02','','890900840-1','Camacol','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF03','','890900842-6','Comfenalco Antioquia CCF','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF04','','890900841-9','Caja de Compensación Familiar de Antioquia','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF05','','890102044-1','Caja de Compensación Familiar Cajacopi Atlántico','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF06','','890102002-2','Combarranquilla','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF07','','890101994-9','Comfamiliar Atlántico','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF08','','890480023-7','Comfenalco Cartagena','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF09','','890480110-1','Caja de Compensación Familiar de Cartagena','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF10','','891800213-8','Comfaboy','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF11','','890806490-5','CCF de Caldas','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF13','','891190047-2','Comfaca','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF14','','891500182-0','Comfacauca','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF15','','892399989-8','Caja de Compensación Familiar Cesar','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF16','','891080005-1','Comfacor','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF21','','860013570-3','Cafam','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF22','','860007336-1','Colsubsidio','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF24','','860066942-7','Caja de Compensación Familiar Compensar','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF26','','860045904-7','Comfacundi','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF29','','891600091-8','CCF del Chocó','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF30','','892115006-5','Caja de Compensación Familiar de La Guajira','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF32','','891180008-2','Comfamiliar del Huila','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF33','','891780093-3','CCF del Magdalena','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF34','','892000146-3','Cofrem Meta','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF35','','891280008-1','CCF de Nariño','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF36','','890500675-6','Caja de Compensación Familiar del Oriente','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF37','','890500516-3','Caja de Comp. Familiar Comfanorte ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF38','','890270275-5','Caja de Comp. Familiar de Barrancabermeja Cafaba ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF39','','890200106-1','Cajasan ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF40','','890201578-7','Comfenalco Santander','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF41','','892200015-5','Caja de Compensación Familiar del Sucre','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF43','','890000381-0','Comfenalco Quindío','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF44','','891480000-1','Comfamiliar Risaralda','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF46','','890704737-0','CCF del Sur del Tolima Cafasur ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF48','','800211025-1','Comfatolima ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF50','','890700148-4','Comfenalco –Tolima','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF56','','890303093-5','Comfenalco Valle','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF57','','890303208-5','Comfandi ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF63','','891200337-8','Caja de Compensación Familiar del Putumayo','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF64','','892400320-5','Cajasai ','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF65','','800003122-6','Caja de Comp Familiar del Amazonas Cafamaz','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF67','','800219488-4','Comfiar Caja de Compensacion Familiar de Arauca','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF68','','800231969-4','Comcaja','',0,1,0,0,0);
INSERT INTO rhu_entidad (codigo_entidad_pk,codigo_interface,direccion,nit,nombre,telefono,arl,ccf,eps,ces,pen) VALUES (0,'CCF69','','844003392-8','Comfacasanare','',0,1,0,0,0);