INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'ANTIOQUIA',05);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'ATLANTICO',08);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'BOGOTA',11);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'BOLIVAR',13);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'BOYACA',15);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CALDAS',17);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CAQUETA',18);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CAUCA',19);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CESAR',20);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CORDOBA',23);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CUNDINAMARCA',25);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CHOCO',27);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'HUILA',41);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'LA GUAJIRA',44);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'MAGDALENA',47);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'META',50);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'NARIÑO',52);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'N. DE SANTANDER',54);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'QUINDIO',63);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'RISARALDA',66);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'SANTANDER',68);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'SUCRE',70);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'TOLIMA',73);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'VALLE DEL CAUCA',76);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'ARAUCA',81);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'CASANARE',85);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'PUTUMAYO',86);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'SAN ANDRES',88);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'AMAZONAS',91);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'GUAINIA',94);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'GUAVIARE',95);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'VAUPES',97);
INSERT INTO gen_departamento ( codigo_departamento_pk, codigo_pais_fk, nombre, codigo_dane) VALUES (0,1,'VICHADA',99);