security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    mario:
                        password: 70143086
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
                path:   /logout
                target: /inicio            
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }                
        - { path: /.*, roles: ROLE_USER }    
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }