<?php

namespace App\Repository\RecursoHumano;

use App\Entity\RecursoHumano\RhuExamenRestriccionMedicaTipo;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuExamenRestriccionMedicaTipoRepository extends ServiceEntityRepository {

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, RhuExamenRestriccionMedicaTipo::class);
    }
    
}